In [1]:
#Question 1
import numpy as np


temperature = np.array([25, 28, 31, 35, 38, 27, 33, 40])

print("Original temperatures:", temperature)


# (a)
corrected_temperature = temperature + 2

print("\nTemperatures after adding 2°C:", corrected_temperature)


# (b)
fahrenheit = (9 / 5) * corrected_temperature + 32

print("\nTemperatures in Fahrenheit:", fahrenheit)


# (c)
greater_than_32 = corrected_temperature[corrected_temperature > 32]

print("\nReadings greater than 32°C:", greater_than_32)


# (d)
count = np.sum(corrected_temperature > 32)

print("Number of readings greater than 32°C:", count)

Original temperatures: [25 28 31 35 38 27 33 40]

Temperatures after adding 2°C: [27 30 33 37 40 29 35 42]

Temperatures in Fahrenheit: [ 80.6  86.   91.4  98.6 104.   84.2  95.  107.6]

Readings greater than 32°C: [33 37 40 35 42]
Number of readings greater than 32°C: 5


In [2]:
#Question 2
import numpy as np


steps = np.array([
    [5000, 6200, 7100],
    [8000, 7500, 9000],
    [4500, 5100, 4800],
    [9000, 8500, 9500]
])

print("Steps matrix:")
print(steps)


# (a)
total_steps = np.sum(steps)

print("\nTotal steps:", total_steps)


# (b)
mean_steps = np.mean(steps)

print("Mean steps:", mean_steps)


# (c)
maximum = np.max(steps)
minimum = np.min(steps)

print("Maximum steps:", maximum)
print("Minimum steps:", minimum)


# (d)
total_each_day = np.sum(steps, axis=0)

print("\nTotal steps for each day:", total_each_day)


# (e)
total_each_user = np.sum(steps, axis=1)

print("Total steps for each user:", total_each_user)


# (f)
max_position = np.argmax(steps)


row, column = np.unravel_index(max_position, steps.shape)

print("\nMaximum value:", steps[row, column])
print("User/Day position of maximum:", (row, column))

Steps matrix:
[[5000 6200 7100]
 [8000 7500 9000]
 [4500 5100 4800]
 [9000 8500 9500]]

Total steps: 84200
Mean steps: 7016.666666666667
Maximum steps: 9500
Minimum steps: 4500

Total steps for each day: [26500 27300 30400]
Total steps for each user: [18300 24500 14400 27000]

Maximum value: 9500
User/Day position of maximum: (np.int64(3), np.int64(2))


In [3]:
#Question 3
import numpy as np

# (a)
original = np.array([1, 2, 3, 4, 5, 6])

print("Original array:")
print(original)


# (b)
subset = original[1:5]

print("\nSubset:")
print(subset)


# (c)
subset[0] = 999

print("\nAfter modifying subset:")
print("Original:", original)
print("Subset:", subset)


# d)
copied_array = original[1:5].copy()


copied_array[0] = 500

print("\nAfter modifying copied array:")
print("Original:", original)
print("Copied array:", copied_array)


# (e)
matrix = np.arange(1, 13).reshape(3, 4)

print("\n3 x 4 Matrix:")
print(matrix)


# (f)

# First row
first_row = matrix[0, :]
print("\nFirst row:")
print(first_row)

# Last row
last_row = matrix[-1, :]
print("\nLast row:")
print(last_row)

# Second column
second_column = matrix[:, 1]
print("\nSecond column:")
print(second_column)

# Rows 1-2 and columns 2-3
# Using Python indexing: rows 1 to 2 = 1:3
# columns 2 to 3 = 2:4
selected_elements = matrix[1:3, 2:4]

print("\nRows 1-2 and columns 2-3:")
print(selected_elements)


# (g)

flattened_array = matrix.flatten()
ravel_array = matrix.ravel()

print("\nFlatten using flatten():")
print(flattened_array)

print("\nFlatten using ravel():")
print(ravel_array)


# h)
ravel_array[0] = 1000

print("\nAfter modifying ravel array:")
print("Ravel array:", ravel_array)
print("Original matrix:")
print(matrix)


# i)
flattened_array[0] = 2000

print("\nAfter modifying flatten array:")
print("Flatten array:", flattened_array)
print("Original matrix:")
print(matrix)


# j)

print("\nProperties of original 3 x 4 matrix:")
print("Shape:", matrix.shape)
print("Dimensions:", matrix.ndim)
print("Size:", matrix.size)
print("Data type:", matrix.dtype)

Original array:
[1 2 3 4 5 6]

Subset:
[2 3 4 5]

After modifying subset:
Original: [  1 999   3   4   5   6]
Subset: [999   3   4   5]

After modifying copied array:
Original: [  1 999   3   4   5   6]
Copied array: [500   3   4   5]

3 x 4 Matrix:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

First row:
[1 2 3 4]

Last row:
[ 9 10 11 12]

Second column:
[ 2  6 10]

Rows 1-2 and columns 2-3:
[[ 7  8]
 [11 12]]

Flatten using flatten():
[ 1  2  3  4  5  6  7  8  9 10 11 12]

Flatten using ravel():
[ 1  2  3  4  5  6  7  8  9 10 11 12]

After modifying ravel array:
Ravel array: [1000    2    3    4    5    6    7    8    9   10   11   12]
Original matrix:
[[1000    2    3    4]
 [   5    6    7    8]
 [   9   10   11   12]]

After modifying flatten array:
Flatten array: [2000    2    3    4    5    6    7    8    9   10   11   12]
Original matrix:
[[1000    2    3    4]
 [   5    6    7    8]
 [   9   10   11   12]]

Properties of original 3 x 4 matrix:
Shape: (3, 4)
Dimensions: 2
Size

In [4]:
#Queston 4
import numpy as np

y = np.array([40, 65, 30, 85])


X = np.array([
    [6, 70, 3],
    [5, 50, 6],
    [8, 80, 2],
    [4, 30, 8]
])


# (a)

print("Shape of X:", X.shape)
print("Dimensions of X:", X.ndim)


# b)

X_T = X.T

print("\nTranspose of X:")
print(X_T)


# c)

XTX = X.T @ X

print("\nX.T @ X:")
print(XTX)


# d)

XTX_inverse = np.linalg.inv(XTX)

print("\nInverse of X.T @ X:")
print(XTX_inverse)


# e)

beta = XTX_inverse @ X.T @ y

print("\nOLS coefficients (beta):")
print(beta)


# f)

print("\nCoefficients:")
print("Sleep coefficient:", beta[0])
print("Activity coefficient:", beta[1])
print("Stress coefficient:", beta[2])


# g)

new_user = np.array([5, 40, 7])

predicted_score = new_user @ beta

print("\nNew user:", new_user)
print("Predicted assistance score:", predicted_score)

Shape of X: (4, 3)
Dimensions of X: 2

Transpose of X:
[[ 6  5  8  4]
 [70 50 80 30]
 [ 3  6  2  8]]

X.T @ X:
[[  141  1430    96]
 [ 1430 14700   910]
 [   96   910   113]]

Inverse of X.T @ X:
[[ 1.10521428 -0.09848746 -0.14581398]
 [-0.09848746  0.00891203  0.01190129]
 [-0.14581398  0.01190129  0.0368847 ]]

OLS coefficients (beta):
[-0.15921454  0.14083853 10.06302242]

Coefficients:
Sleep coefficient: -0.1592145415946895
Activity coefficient: 0.14083852991906243
Stress coefficient: 10.063022422714587

New user: [ 5 40  7]
Predicted assistance score: 75.27862544779117
