In [1]:
#Question 1

import numpy as np

array = np.array([100, 201, 301, 400, 501])
print("Original array:", array)

print("After adding 2:", array + 2)

print("After multiplying by 3:", array * 3)

print("After dividing by 2:", array / 2)

Original array: [100 201 301 400 501]
After adding 2: [102 203 303 402 503]
After multiplying by 3: [ 300  603  903 1200 1503]
After dividing by 2: [ 50.  100.5 150.5 200.  250.5]


In [6]:
#Question 2(a)

import numpy as np

array = np.array([11, 22, 33, 66, 44,55])
reversed_arr = array[::-1]

print("Original array:", array)
print("Reversed array:", reversed_arr)

#2(b)(i)
import numpy as np

x = np.array([1,2,3,4,5,1,2,1,1,1])

#unique values and their frequencies
values, counts = np.unique(x, return_counts=True)

#most frequent value
most_frequent = values[np.argmax(counts)]

#its indices
indices = np.where(x == most_frequent)[0]

print("Array x:", x)
print("Most frequent value:", most_frequent)
print("Number of times it occurs:", counts[np.argmax(counts)])
print("Indices:", indices)

#2(b)(ii)
import numpy as np

y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3])

#unique values and their frequencies
values, counts = np.unique(y, return_counts=True)

#most frequent value
most_frequent = values[np.argmax(counts)]

#indices
indices = np.where(y == most_frequent)[0]

print("Array y:", y)
print("Most frequent value:", most_frequent)
print("Number of times it occurs:", counts[np.argmax(counts)])
print("Indices:", indices)



Original array: [11 22 33 66 44 55]
Reversed array: [55 44 66 33 22 11]
Array x: [1 2 3 4 5 1 2 1 1 1]
Most frequent value: 1
Number of times it occurs: 5
Indices: [0 5 7 8 9]
Array y: [1 1 1 2 3 4 2 4 3 3]
Most frequent value: 1
Number of times it occurs: 3
Indices: [0 1 2]


In [7]:
#Question 3
import numpy as np

arr = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])

print("Array:")
print(arr)

# (a)
print("1st row, 2nd column:", arr[0, 1])

# (b)
print("3rd row, 1st column:", arr[2, 0])

Array:
[[10 20 30]
 [40 50 60]
 [70 80 90]]
1st row, 2nd column: 20
3rd row, 1st column: 70


In [8]:
#Question 4
import numpy as np

gagandeep = np.linspace(10, 100, 25)

print("Array:")
print(gagandeep)

# Dimensions of the array
print("\nDimensions:", gagandeep.ndim)

# Shape of the array
print("Shape:", gagandeep.shape)

# Total number of elements
print("Total elements:", gagandeep.size)

# Data type of each element
print("Data type:", gagandeep.dtype)

# Total number of bytes consumed
print("Total bytes:", gagandeep.nbytes)

# Transpose using reshape()
transpose_gagandeep = gagandeep.reshape(25, 1)

print("\nTranspose using reshape():")
print(transpose_gagandeep)

# Transpose using T attribute
transpose_using_T = gagandeep.T

print("\nTranspose using T:")
print(transpose_using_T)

Array:
[ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]

Dimensions: 1
Shape: (25,)
Total elements: 25
Data type: float64
Total bytes: 200

Transpose using reshape():
[[ 10.  ]
 [ 13.75]
 [ 17.5 ]
 [ 21.25]
 [ 25.  ]
 [ 28.75]
 [ 32.5 ]
 [ 36.25]
 [ 40.  ]
 [ 43.75]
 [ 47.5 ]
 [ 51.25]
 [ 55.  ]
 [ 58.75]
 [ 62.5 ]
 [ 66.25]
 [ 70.  ]
 [ 73.75]
 [ 77.5 ]
 [ 81.25]
 [ 85.  ]
 [ 88.75]
 [ 92.5 ]
 [ 96.25]
 [100.  ]]

Transpose using T:
[ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]


In [9]:
#Question 5

import numpy as np

ucs420_gagandeep = np.array([
    [10, 20, 30, 40],
    [50, 60, 70, 80],
    [90, 15, 20, 35]
])

print("Original Array:")
print(ucs420_gagandeep)


#  mean
print("\nMean:", np.mean(ucs420_gagandeep))

#  median
print("Median:", np.median(ucs420_gagandeep))

# maximum
print("Maximum:", np.max(ucs420_gagandeep))

# minimum
print("Minimum:", np.min(ucs420_gagandeep))

# unique elements
print("Unique elements:", np.unique(ucs420_gagandeep))


# Reshape to 4 rows and 3 columns
reshaped_ucs420_gagandeep = ucs420_gagandeep.reshape(4, 3)

print("\nReshaped Array (4 x 3):")
print(reshaped_ucs420_gagandeep)


# Resize to 2 rows and 3 columns
resized_ucs420_gagandeep = np.resize(ucs420_gagandeep, (2, 3))

print("\nResized Array (2 x 3):")
print(resized_ucs420_gagandeep)

Original Array:
[[10 20 30 40]
 [50 60 70 80]
 [90 15 20 35]]

Mean: 43.333333333333336
Median: 37.5
Maximum: 90
Minimum: 10
Unique elements: [10 15 20 30 35 40 50 60 70 80 90]

Reshaped Array (4 x 3):
[[10 20 30]
 [40 50 60]
 [70 80 90]
 [15 20 35]]

Resized Array (2 x 3):
[[10 20 30]
 [40 50 60]]
